[theme]
base = "light"
primaryColor = "#2a78d6"
backgroundColor = "#f9f9f7"
secondaryBackgroundColor = "#f2f0ec"
textColor = "#0b0b0b"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
